// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbttwuvanlhblzljphvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRidHR3dXZhbmxoYmx6bGpwaHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzcyMTYsImV4cCI6MjA1ODIxMzIxNn0.Kn_ln18BktZ6pHrfcmMJiKBqCJUsrIK1xuFKENfasDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);